### ISSUE TITLE
provide an example / use case

### ISSUE THREAD

**Issue by x0rzkov** [calebglawson/twint-sklearn-twitter-classifier#1]
Hi,

Hope you are all well !

Could you provide an example for the watchlist.csv ? 
My use case is to check accounts declared by XYZ

Cheers,
X

**Comment by calebglawson** [comment]
```watchlist.csv``` is primarily used when computing the stats generated by ```gather_data.py```.  It contains the list of users that are searched for in other user's (as supplied by the ```--userlist``` or ```--username``` command) follows, likes, retweets, and mentions.  These stats are essentially a way to measure a given user's level of engagement with the users on the watchlist.

The goal of this tool is to produce a machine learning model that can be used to identify users that also belong on the watchlist.  I will outline a theoretical usecase below.

Let's say you have an account, XYZ, that has built up a list of users.  ```watchlist.csv``` would contain all users, with active accounts, that XYZ has listed as belonging to a particular group.  In order to create the machine learning model, you also need to make another list with an equal amount of users that do not belong to the target group (```watchlist.csv```).  One would then make a combined list, ```userlist.csv```, containing the users that belong on the list, as well as users that do not belong on the list. ```gather_data.py``` would then gather data for all the users listed within userlist.csv, while using ```watchlist.csv``` to calculate the stats.

The example command for generating a model, in this scenario would be:
```python model_pipeline.py watchlist.csv --userlist userlist.csv```

**Comment by calebglawson** [comment]
Added an example use case to the Summary in readme.md to address this issue.
